# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            阿江博客
tagline:          'bryanluo'
description:      '这里记录着我的学习过程，学习从写作开始'
url:              https://bryanluo.github.io
baseurl:          '/'
head_url:         'https://avatars1.githubusercontent.com/u/20706487?s=460&amp;u=a57a7ebc60a7578805ad761a4b64490375fb333e&amp;v=4'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'bryanluo'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
